### PR TITLE
probable error fix

### PR DESCRIPTION
**Pull request by kamenik**
This is typo & bug i suppose.

### CODE REVIEW

**Comment by bgrozev** [comment]
Thank you for your contribution! Before we accept it we need you to sign our contributor agreement[1]. Please send it to support@bluejimp.com. Apologies for the inconvenience, but unfortunately we cannot avoid it.

[1] http://bluejimp.com/bca.pdf

**Comment by kamenik** [comment]
Is it ok?

**Comment by bgrozev** [comment]
Received, thanks! Just waiting for a confirmation.

**Comment by bgrozev** [comment]
@kamenik, sorry for the hassle but could you please scan this and resend it, as the photo has text which isn't readable?

**Comment by ibauersachs** [comment]
Not sure what your CLA status is. In any case, we moved to an [all-electronic process](https://jitsi.org/icla) and everybody is/was required to re-sign there.

**Comment by ibauersachs** [comment]
@bgrozev can you please check the CLA or fix these manually?

**Pull request closed without merging**
