### PR TITLE
brand: GitHub

### PR DESCRIPTION
**Pull request by jsoref**
This is one logical PR / commit for a very minor thing.

It's different from my primary objective, so...

### CODE REVIEW

**Comment by jsoref** [comment]
@Atrate: what other steps are required for this PR?

**Comment by Atrate** [comment]
I am not a person that has merging permissions. Ask someone, who does.

**Comment by jsoref** [comment]
@ibauersachs ?

**Comment by ibauersachs** [comment]
Hi, thanks for your contribution!
If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

**Comment by jsoref** [comment]
I signed on March 22...

**Comment by jsoref** [comment]
DocuSign Envelope ID: AD48B7F0-9876-401F-8198-8B4ADD851F6D

Maybe the instructions are unclear. I naively assumed that my act of docusigning was sufficient. Did I need to forward the pdf?

**Comment by damencho** [comment]
Now I see it.

**Comment by damencho** [comment]
@ibauersachs Sorry, I was searching for it but did not find it. Not sure what happen. But now I see it. Sorry for the confusion.

**Comment by damencho** [comment]
Now I see, the problem was that the name on github account does not exactly match the one from the document and I was searching by name.

**Comment by jsoref** [comment]
Ah. That's the problem w/ forms that ask for "full name" instead of "name". No worries.

(I'm sure it didn't help that the email address I'm using for commits is noreply...)

**Pull request merged**
