### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Hi... This PR was developed using https://github.com/marketplace/actions/check-spelling

I'm happy to split/squash PRs w/in reason.

Do note that this PR currently has 446 commits and GitHub has a 250 commit limit, which means you really can't use the GitHub **Commits** UI to review -- you can use **Files changed**.

There's one change which is **not correct** as I can't figure out what it's trying to say:
https://github.com/jsoref/jitsi/blob/1db3d0966a3c8cf83f2ab2cad032a0e15385568d/src/net/java/sip/communicator/plugin/notificationconfiguration/SoundFilter.java#L73

I've mostly tried to skip over localizations and binaries. I may have occasionally messed up, if so, I'm sorry. I did leave some changes to localizations where I renamed the localization key itself. (I made one conscious change to the ast localization: `impl.googlecontacts.CONFIG_FORM_TITLE` => `Google Contacts` as there's no evidence that `Contacs` is a word in that language -- in fact, the word appears to be `contautu`.) 

I generally try to skip upstream files, but I didn't see a large number of such files. (The only suspicious ones are bzlib/lzma.) -- If you identify files that are upstreams, I'm happy to skip them and will probably eventually send fixes to them directly.

Often I'm asked to split between docs/comments/tests/prod code. I can slice one or two ways as requested, but in general I find it's best to work on a term-by-term basis e.g. maybe someone objects to my change to `timed-out` -- in which case, undoing it globally is best.

### CODE REVIEW

**Comment by damencho** [comment]
What is the reason for this? I don't think this makes much sense ... especially changing names of configuration parameters will break stuff.

**Comment by jsoref** [comment]
Some of these changes are effectively bug fixes, there were spelling errors resulting in incorrect paths.

I'm happy to drop things which are problematic.

Misspellings make it harder for people to understand code. It's harder to search for things, it's harder to understand what things are supposed to do...

**Comment by ibauersachs** [comment]
I think I'm going to flat out reject this. Too big to review. I'm happy with actual bugfixes, e.g. broken paths. But typos in comments or method names as a mass-refactoring: no.

**Comment by jsoref** [comment]
@ibauersachs would something akin to this https://github.com/jitsi/jitsi/compare/master...jsoref:spelling-subset be acceptable? Would you want it split further?

**Comment by ibauersachs** [comment]
Ahm, look, I'm working on this branch: https://github.com/jitsi/jitsi/tree/new-gradle-build
It also modifies the entire tree and whatever you contribute right now will conflict with that. It's not that I don't appreciate what you're doing here, quite the contrary, but (sorry, there's always the but): can you hold off with the changes until I'm through, even with smaller stuff?

Later, if the PRs are smaller, reviewable and don't contain changes to config properties, then yes please bring them! :-)

**Comment by jsoref** [comment]
Just ping me when you're open to things. It's fairly trivial for me to rebase (including conceptually, my tooling can try to recalculate how to make the same changes to different files).

Beyond that, I just need guidelines for how to shape the PRs so that they're sufficiently bite-sized. (Like, would you have wanted the different commits in that branch to be individual PRs?)

My long term goal is to try to give projects a tool which can help them hold off new typos and then gradually reduce their codebase's typos.

**Comment by ibauersachs** [comment]
Not quite sure how to proceed. Surely stuff like the broken spellcheck path is best, next typos in method names. Javadoc typos are of least concern.

I guess if I can somehow skip reviewing everything and guarantee that only comments were modified, a larger PR for that should be okay.

**Comment by jsoref** [comment]
* You have one class which is misspelled (that involves a file rename because Java).
* Method names are fairly easy to split out (there are only 25 java files that appear to have method name changes).
* Local variables are fairly easy to split out.
* It's also pretty easy to split out localization identifiers.
* It's possible to split out output changes (I did that in preparing `spelling-subset`, although for the debug bits, it seemed like it would be too much, so I didn't include that commit)

* Javadoc can either be done w/ general comments or separately. It's pretty easy to split them out either way.

When I get to PRs like that, I generally add review comments to draw attention to the things I'm least certain about, although for this size, I might just shunt them off to an additional PR. 

Fwiw, it wasn't terribly expensive for me to make the small subset in `spelling-subset` -- under an hour.

Anyway, just ping me when you're ready and I can take it from that list (or another)

**Pull request closed without merging**
