### PR TITLE
Improve add contact dialog

### PR DESCRIPTION
**Pull request by tomka**
This pull request contains some commits discussed in pull request #13. It contains only those changes to the "Add contact" dialog were most people could agree on. Three changes were made: 1. Group field has been moved to bottom 2. Tool tips have been added and 3. example prompts have been added to the input fields. This is how the dialog now looks like:

jitsi_improved_add_contact_dialog

All other changes from #13 remain there for discussion.

### CODE REVIEW

**Comment by ibauersachs** [comment]
Hi, thanks for your contribution!
If you haven't already done so, could you please make sure you sign our CLA (https://jitsi.org/icla for individuals and https://jitsi.org/ccla for corporations)? We would unfortunately be unable to merge your patch unless we have that piece :(.

**Comment by tomka** [comment]
Thanks for getting back to this pull request! In case there is still interest in merging this: I signed your CLA back in 2014. Let me know if I should send it again.

**Comment by ibauersachs** [comment]
@tomka there is a new CLA in effect since BlueJimp was acquired by Atlassian in spring '15. Everyone has/had to sign the new one (see links above and sorry for the confusion).

**Comment by tomka** [comment]
Oh I see, thanks for the clarification. I will send a signed copy of the new CLA then.

**Pull request closed without merging**
