### PR TITLE
feat: Updates latest libjitsi and clears stats on participant leave.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Review by gpolitis — APPROVED** [review]

**Comment by sergiomb2** [comment]
latest libjitsi  jar libjitsi-1.0-55-gcdf3e894.jar requires a requires a different jna.jar [1] is breaks the startup with lots of messages like this one [2] 

[1]
```
+Import-Package: ch.imvs.sdes4j.srtp;version="[1.1,2)",com.ibm.media.co^M
+ dec.audio;version="[1.0,2)",com.sun.jna;version="[5.5,6)",com.sun.jna^M
+ .ptr;version="[5.5,6)",com.sun.jna.win32;version="[5.5,6)"
```
[2]
org.osgi.framework.BundleException: Unable to resolve net.java.sip.communicator.plugin.simpleaccreg [150](R 150.0): missing requirement [net.java.sip.communicator.plugin.simpleaccreg [150](R 150.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.service.gui) [caused by: Unable to resolve net.java.sip.communicator.service.gui [58](R 58.0): missing requirement [net.java.sip.communicator.service.gui [58](R 58.0)] osgi.wiring.package; (osgi.wiring.package=org.jitsi.service.resources) [caused by: Unable to resolve org.jitsi.libjitsi [126](R 126.0): missing requirement [org.jitsi.libjitsi [126](R 126.0)] **osgi.wiring.package; (&(osgi.wiring.package=com.sun.jna)(version>=5.5.0)(!(version>=6.0.0)))]]** Unresolved requirements: [[net.java.sip.communicator.plugin.simpleaccreg [150](R 150.0)] osgi.wiring.package; (osgi.wiring.package=net.java.sip.communicator.service.gui)]

**Comment by Af0x** [comment]
Hello @damencho, can you please look into this again and either fix or revert this? Thanks and best regards

**Comment by ibauersachs** [comment]
This is already fixed in the new-build branch, there's nothing to revert.

**Comment by Af0x** [comment]
Thanks, cloned the new-build branch and it works.

**Comment by Af0x** [comment]
I have to come back to this. As long as the new-build branch isn´t stable it would be really nice if you could provide a fix for the master/stable branch so that further fixes can also be incorporated by those that need a stable version. As this is described as feature, maybe you should really withdraw it or, as said, provide a solution that has nothing to do with the new-build branch.

**Pull request merged**
