### PR TITLE
Fixes all chat windows being closed...

### PR DESCRIPTION
**Pull request by veteran29**
Fixes all chat windows being closed when grouping of chat windows is disabled.

### CODE REVIEW

**Comment by ibauersachs** [comment]
Thank you for your contribution! Before we can accept it we need you to sign our [contributor agreement](http://bluejimp.com/bca.pdf). Please send it to support@bluejimp.com. Apologies for the inconvenience, but unfortunately we cannot avoid it.
(If you've already done that, apologies, and please state it here.)

**Comment by veteran29** [comment]
Sent ;-)

**Comment by ibauersachs** [comment]
Thank you and sorry for the delay! Could you perhaps scan the document instead of taking a photo? Your signature is almost unrecognizable...

**Comment by veteran29** [comment]
I have sent updated photos, they should be fine. Sorry for inconvenience but i have no access to scanner at the moment.

**Pull request merged**
