### PR TITLE
Introduce SmackInteroperabilityLayer for abstracting different Smack implementations (3 and 4)

### PR DESCRIPTION
**Pull request by mksh**
- base class for abstracting Smack
- implementation for SmackV3

### CODE REVIEW

**Comment by ibauersachs** [comment]
Would someone mind explaining to me what this is good for?

**Comment by bgrozev** [comment]
Ingo, we are adding BOSH support to jitsi-hammer, which uses the smack extensions from the Jitsi bundle. For this we updated jitsi-hammer's smack to version 4, and @mksh created an abstraction layer, so we can reuse the code and facilitate the potential future migration for Jitsi. A smack4 implementation of the layer will be added to jitsi-hammer soon.

**Comment by ibauersachs** [comment]
Thanks Boris. I never really looked into it and thus cannot estimate the amount of work required. But wouldn't it make more sense to upgrade Jitsi to Smack V4 for the benefit of all involved projects instead of writing abstraction layers and procrastinating the inevitable?

**Comment by bgrozev** [comment]
I can't estimate the effort accurately either, but I would tend to think it would be substantial. I also suspect it would introduce bugs, which we wouldn't have the time to fix. In any case, I don't think adding this layer is procrastination -- rather, it is an actual step towards migrating, since part of the code is now v4-ready (or at least v4.0.7-ready).

**Comment by damencho** [comment]
I just wanted to check which of our patches had been integrated there, I suspect most of them, but I can spent some time on this and report it.

**Pull request merged**
