### PR TITLE
Fix the issue with IP-address in uri for the xmpp call from a command line

### PR DESCRIPTION
**Pull request by r3code**
Allow use IP-addreses after `@` in contact uri, e.g. `user@192.168.0.1`.

### CODE REVIEW

**Comment by ibauersachs** [comment]
Could you please make sure that you've signed the [CLA](https://jitsi.org/icla)?

**Comment by r3code** [comment]
@ibauersachs I've signed the CLA, can you check? Or how can I show it to you?

**Comment by damencho** [comment]
@r3code When did you sign it? I don't see it right now in the list of all signed cla?

**Comment by r3code** [comment]
@damencho see it here https://na2.docusign.net/Signing/EmailStart.aspx?a=7649afe5-3ed0-4958-8c50-32db64398983&r=0e9df101-eaf8-480a-afe1-9991fe3ad11e&cookiecheck=1

**Pull request merged**
