### PR TITLE
Debian: Allow Jitsi to be started in Terminal

### PR DESCRIPTION
**Pull request by traud**
Furthermore, do not require Bash but just any POSIX shell.

### CODE REVIEW

**Comment by traud** [comment]
Actually, the problem was the `echo`; if started from the Terminal, Jitsi Desktop started from background and no System.out was printed to the Terminal. Because I removed the `echo`, the `exec` was not needed anymore. Not sure why `command -v` and `bash` were used/required. I lifted that as well. Tested for [POSIX compliance …](https://unix.stackexchange.com/q/48786)

**Comment by ibauersachs** [comment]
The echo was proabably debugging stuff that I forgot to remove. `command -v` was for some reason necessary, you could probably search old PRs/issues and find something (probably with `which` though).

**Comment by traud** [comment]
That file was created with the Gradle build commit. When looking at its [parent commit](https://github.com/jitsi/jitsi/tree/345a7c83911984d049eeb88f00958cc8ed60c2ea/resources/install), I do not find any shell command file which uses `which` or `command -v`. Are you saying that there was an issue report … and I should keep that `command -v java` so this Pull Request get merged?

**Comment by ibauersachs** [comment]
It was introduced in d86bf7cc8955bdbdd758a8161fdb8abbb62ef7f6. I had some memories of there being a bug report, but it's possible this isn't relevant anymore (or never was).

**Pull request merged**
